### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-arsenic#39]
After fixing #38, it would be useful to cut a new release!

@mikemhenry : Can you help with this?

**Comment by mikemhenry** [comment]
Sure! I'll use this checklist:
- [ ] Make PR to update the change log
- [ ] Make a tag + GitHub release 
- [ ] Merge in conda-forge feedstock PR

I'll make sure you approve the PRs before I merge them @jchodera

**Comment by mikemhenry** [comment]
@jchodera we don't have a changelog, should we start one? Also, is it okay if I change the default branch name to `main` after the release?

**Comment by jchodera** [comment]
Yes and yes! Thanks!

**Comment by mikemhenry** [comment]
This will be fixed with https://github.com/conda-forge/arsenic-feedstock/pull/4
